version: '2.0'
services:
  # ... Database configs
  database:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME:admin
      - MONGO_INITDB_ROOT_PASSWORD:ikanlele123Bas
    ports: 
        - 27017:27017
    volumes:
      - /my/custom:/etc/mongo
    
